***Settings***

Library   RequestsLibrary
Library   JSONLibrary
Library   Collections
Library    ../../libraries/Excel.py
Library    OperatingSystem

Resource   common.resource
Resource   Excel.resource
Resource   ../business/github/get_request_gitHub.resource
Resource   ../business/regres/request_regres.resource
Resource   ../business/testingworld/requests_testingworld.resource
Resource   ../../variables/business/variables_github.resource
Resource   ../../variables/business/variables_regres.resource
Resource   ../../variables/business/variables_testingworld.resource
